version: '3.8'

services:
  backend:
    image: e11824496/adl:backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    image: e11824496/adl:frontend
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
