version: '3.8'

services:
  backend:
    image: your-backend-image
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    image: your-frontend-image # Replace with your Streamlit frontend image name
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
